#! /usr/bin/env node
// build a deployment-ready package

const metalsmith = require('metalsmith');
const {execFileSync} = require('child_process');
const html = require('metalsmith-in-place');
const {resolve} = require('path');

process.chdir(`${__dirname}/..`);
const source = 'source';
const destination = 'public';

execFileSync('git', ['checkout', destination]);
execFileSync('git', ['clean', '-dxf', destination]);

const app = metalsmith(process.cwd())
    .clean(false)
    .source(source)
    .destination(destination)
    .use(html());

if (module.parent) {
    module.exports = app;
} else {
    app.build(error => {
        if (error) {
            throw error;
        }
    });
}
