#! /usr/bin/env node
const metalsmith = require('metalsmith');
const {execFileSync} = require('child_process');

const destination = `${__dirname}/../public/`;
execFileSync('git', ['checkout', destination]);
execFileSync('git', ['clean', '-dxf', destination]);

const app = metalsmith(`${__dirname}/..`)
    .clean(false)
    .source('./source')
    .destination(destination);

if (module.parent) {
    module.exports = app;
} else {
    app.build(error => {
        if (error) throw error;
    });
}
