#! /usr/bin/env bash
# watch files for changes, serve and live reload the site and the build

scripts="$(dirname "$0")"
"$scripts"/../node_modules/.bin/node-dev \
    --no-notify \
    "$scripts"/.internals/develop "$@"
